import type { NormalizedDeal } from '@/types'
import { addDays, addHours, subHours } from 'date-fns'

const now = new Date()

// All cover images use Steam CDN (cdn.akamai.steamstatic.com) which is reliable
// and doesn't block hotlinking. App IDs verified correct.
export const MOCK_DEALS: NormalizedDeal[] = [
  {
    id: 'epic-001',
    title: 'Alan Wake 2',
    platform: 'epic',
    originalPrice: 59.99,
    currentPrice: 0,
    currency: 'USD',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1145360/capsule_616x353.jpg',
    claimUrl: 'https://store.epicgames.com/en-US/free-games',
    startDate: subHours(now, 24).toISOString(),
    endDate: addDays(now, 6).toISOString(),
    dealType: 'timed-free',
    genres: ['action', 'adventure', 'horror'],
    description: 'The long-awaited sequel to the cult classic survival horror game.',
    igdbRating: 89,
    developer: 'Remedy Entertainment',
    fetchedAt: subHours(now, 2).toISOString(),
    hoursLeft: 6 * 24,
    isExpiringSoon: false,
    isFresh: true,
  },
  {
    id: 'gog-001',
    title: 'Disco Elysium – The Final Cut',
    platform: 'gog',
    originalPrice: 39.99,
    currentPrice: 0,
    currency: 'USD',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/632470/capsule_616x353.jpg',
    claimUrl: 'https://www.gog.com/en/game/disco_elysium_the_final_cut',
    startDate: subHours(now, 12).toISOString(),
    endDate: addDays(now, 3).toISOString(),
    dealType: 'timed-free',
    genres: ['rpg', 'adventure'],
    igdbRating: 96,
    developer: 'ZA/UM',
    fetchedAt: subHours(now, 1).toISOString(),
    hoursLeft: 3 * 24,
    isExpiringSoon: false,
    isFresh: true,
  },
  {
    id: 'epic-002',
    title: 'Control Ultimate Edition',
    platform: 'epic',
    originalPrice: 39.99,
    currentPrice: 0,
    currency: 'USD',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/870780/capsule_616x353.jpg',
    claimUrl: 'https://store.epicgames.com/en-US/free-games',
    startDate: subHours(now, 48).toISOString(),
    endDate: addHours(now, 18).toISOString(),
    dealType: 'timed-free',
    genres: ['action', 'adventure'],
    igdbRating: 85,
    developer: 'Remedy Entertainment',
    fetchedAt: subHours(now, 6).toISOString(),
    hoursLeft: 18,
    isExpiringSoon: true,
    isFresh: false,
  },
  {
    id: 'prime-001',
    title: 'Mass Effect Legendary Edition',
    platform: 'prime',
    originalPrice: 59.99,
    currentPrice: 0,
    currency: 'USD',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1328670/capsule_616x353.jpg',
    claimUrl: 'https://gaming.amazon.com',
    startDate: subHours(now, 72).toISOString(),
    endDate: addDays(now, 12).toISOString(),
    dealType: 'timed-free',
    genres: ['rpg', 'action', 'adventure'],
    igdbRating: 93,
    developer: 'BioWare',
    fetchedAt: subHours(now, 4).toISOString(),
    hoursLeft: 12 * 24,
    isExpiringSoon: false,
    isFresh: false,
  },
  {
    id: 'steam-001',
    title: "Baldur's Gate 3",
    platform: 'steam',
    originalPrice: 59.99,
    currentPrice: 0,
    currency: 'USD',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1086940/capsule_616x353.jpg',
    claimUrl: 'https://store.steampowered.com/app/1086940',
    startDate: subHours(now, 6).toISOString(),
    endDate: addDays(now, 2).toISOString(),
    dealType: 'free-weekend',
    genres: ['rpg', 'strategy', 'adventure'],
    igdbRating: 96,
    metacriticScore: 96,
    developer: 'Larian Studios',
    fetchedAt: subHours(now, 1).toISOString(),
    hoursLeft: 2 * 24,
    isExpiringSoon: false,
    isFresh: true,
  },
  {
    id: 'gog-002',
    title: 'Cyberpunk 2077',
    platform: 'gog',
    originalPrice: 49.99,
    currentPrice: 0,
    currency: 'USD',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1091500/capsule_616x353.jpg',
    claimUrl: 'https://www.gog.com/game/cyberpunk_2077',
    startDate: subHours(now, 36).toISOString(),
    endDate: addHours(now, 4).toISOString(),
    dealType: 'timed-free',
    genres: ['action', 'rpg'],
    igdbRating: 88,
    metacriticScore: 86,
    developer: 'CD Projekt Red',
    fetchedAt: subHours(now, 5).toISOString(),
    hoursLeft: 4,
    isExpiringSoon: true,
    isFresh: false,
  },
  {
    id: 'itch-001',
    title: 'Celeste',
    platform: 'itch',
    originalPrice: 19.99,
    currentPrice: 0,
    currency: 'USD',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/504230/capsule_616x353.jpg',
    claimUrl: 'https://mattmakesgames.itch.io/celeste',
    startDate: subHours(now, 10).toISOString(),
    endDate: addDays(now, 7).toISOString(),
    dealType: 'timed-free',
    genres: ['platformer', 'indie'],
    igdbRating: 92,
    developer: 'Maddy Thorson & Noel Berry',
    fetchedAt: subHours(now, 3).toISOString(),
    hoursLeft: 7 * 24,
    isExpiringSoon: false,
    isFresh: true,
  },
  {
    id: 'humble-001',
    title: 'Hades',
    platform: 'humble',
    originalPrice: 24.99,
    currentPrice: 0,
    currency: 'USD',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1145360/capsule_616x353.jpg',
    claimUrl: 'https://www.humblebundle.com',
    startDate: subHours(now, 5).toISOString(),
    endDate: null,
    dealType: 'permanent-free',
    genres: ['action', 'indie', 'rpg'],
    igdbRating: 93,
    metacriticScore: 93,
    developer: 'Supergiant Games',
    fetchedAt: subHours(now, 5).toISOString(),
    hoursLeft: null,
    isExpiringSoon: false,
    isFresh: true,
  },
  {
    id: 'epic-003',
    title: 'The Outer Worlds',
    platform: 'epic',
    originalPrice: 39.99,
    currentPrice: 0,
    currency: 'USD',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1426420/capsule_616x353.jpg',
    claimUrl: 'https://store.epicgames.com/en-US/free-games',
    startDate: subHours(now, 20).toISOString(),
    endDate: addDays(now, 5).toISOString(),
    dealType: 'timed-free',
    genres: ['rpg', 'action', 'shooter'],
    igdbRating: 82,
    developer: 'Obsidian Entertainment',
    fetchedAt: subHours(now, 2).toISOString(),
    hoursLeft: 5 * 24,
    isExpiringSoon: false,
    isFresh: true,
  },
  {
    id: 'epic-004',
    title: "Death Stranding Director's Cut",
    platform: 'epic',
    originalPrice: 49.99,
    currentPrice: 0,
    currency: 'USD',
    // App ID 1850570 = Death Stranding Director's Cut on Steam
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1850570/capsule_616x353.jpg',
    claimUrl: 'https://store.epicgames.com/en-US/free-games',
    startDate: subHours(now, 8).toISOString(),
    endDate: addDays(now, 4).toISOString(),
    dealType: 'timed-free',
    genres: ['action', 'adventure'],
    igdbRating: 87,
    metacriticScore: 85,
    developer: 'Kojima Productions',
    fetchedAt: subHours(now, 1).toISOString(),
    hoursLeft: 4 * 24,
    isExpiringSoon: false,
    isFresh: true,
  },
  {
    id: 'prime-002',
    title: 'Red Dead Redemption 2',
    platform: 'prime',
    originalPrice: 59.99,
    currentPrice: 0,
    currency: 'USD',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1174180/capsule_616x353.jpg',
    claimUrl: 'https://gaming.amazon.com',
    startDate: subHours(now, 3).toISOString(),
    endDate: addDays(now, 9).toISOString(),
    dealType: 'timed-free',
    genres: ['action', 'adventure'],
    igdbRating: 97,
    metacriticScore: 97,
    developer: 'Rockstar Games',
    fetchedAt: subHours(now, 1).toISOString(),
    hoursLeft: 9 * 24,
    isExpiringSoon: false,
    isFresh: true,
  },
  {
    id: 'steam-002',
    title: 'Elden Ring',
    platform: 'steam',
    originalPrice: 59.99,
    currentPrice: 0,
    currency: 'USD',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1245620/capsule_616x353.jpg',
    claimUrl: 'https://store.steampowered.com/app/1245620',
    startDate: subHours(now, 4).toISOString(),
    endDate: addDays(now, 1).toISOString(),
    dealType: 'free-weekend',
    genres: ['action', 'rpg'],
    igdbRating: 96,
    metacriticScore: 96,
    developer: 'FromSoftware',
    fetchedAt: subHours(now, 2).toISOString(),
    hoursLeft: 24,
    isExpiringSoon: false,
    isFresh: true,
  },
]
